INSERT INTO users (username, name, location) VALUES
('user1', 'John Doe', 'New York'),
('user2', 'Jane Smith', 'Los Angeles'),
('user3', 'Robert Johnson', 'Chicago'),
('user4', 'Emily Davis', 'Houston'),
('user5', 'Michael Brown', 'Phoenix'),
('user6', 'Sarah Wilson', 'Philadelphia'),
('user7', 'David Lee', 'San Antonio'),
('user8', 'Jessica Martinez', 'San Diego'),
('user9', 'James Anderson', 'Dallas'),
('user10', 'Laura Thomas', 'San Jose'),
('user11', 'Daniel Taylor', 'Austin'),
('user12', 'Megan White', 'Jacksonville'),
('user13', 'Chris Harris', 'San Francisco'),
('user14', 'Olivia Robinson', 'Columbus'),
('user15', 'William Walker', 'Indianapolis'),
('user16', 'Emma Young', 'Fort Worth'),
('user17', 'Joshua Allen', 'Charlotte'),
('user18', 'Sophia King', 'Seattle'),
('user19', 'Jacob Wright', 'Denver'),
('user20', 'Isabella Scott', 'Boston'),
('user21', 'Matthew Adams', 'El Paso'),
('user22', 'Ava Moore', 'Nashville'),
('user23', 'Ethan Nelson', 'Detroit'),
('user24', 'Mia Carter', 'Memphis'),
('user25', 'Alexander Harris', 'Baltimore'),
('user26', 'Charlotte Lewis', 'Milwaukee'),
('user27', 'Liam Robinson', 'Albuquerque'),
('user28', 'Zoe Wright', 'Tucson'),
('user29', 'Mason Green', 'Fresno'),
('user30', 'Harper Martinez', 'Sacramento'),
('user31', 'Eli Young', 'Kansas City'),
('user32', 'Lily Hall', 'Mesa'),
('user33', 'Noah Adams', 'Virginia Beach'),
('user34', 'Chloe Scott', 'Atlanta'),
('user35', 'Oliver Harris', 'Colorado Springs'),
('user36', 'Ella Nguyen', 'Omaha'),
('user37', 'Benjamin Thompson', 'Raleigh'),
('user38', 'Avery King', 'Miami'),
('user39', 'Henry Miller', 'Cleveland'),
('user40', 'Mia Wright', 'Tulsa'),
('user41', 'Jackson Walker', 'Oakland'),
('user42', 'Amelia Johnson', 'Minneapolis'),
('user43', 'Lucas White', 'Wichita'),
('user44', 'Eleanor Lee', 'Arlington'),
('user45', 'James Robinson', 'Bakersfield'),
('user46', 'Charlotte Walker', 'Tampa'),
('user47', 'Aiden Harris', 'Aurora'),
('user48', 'Zoe Scott', 'Honolulu'),
('user49', 'Mason Clark', 'Anaheim'),
('user50', 'Isabella Young', 'Riverside');


INSERT INTO Leaderboard (username, wins) VALUES
('user1', 10),
('user2', 15),
('user3', 20),
('user4', 8),
('user5', 12),
('user6', 9),
('user7', 14),
('user8', 11),
('user9', 7),
('user10', 13),
('user11', 10),
('user12', 6),
('user13', 15),
('user14', 20),
('user15', 8),
('user16', 12),
('user17', 9),
('user18', 14),
('user19', 11),
('user20', 7),
('user21', 13),
('user22', 10),
('user23', 6),
('user24', 15),
('user25', 20),
('user26', 8),
('user27', 12),
('user28', 9),
('user29', 14),
('user30', 11),
('user31', 7),
('user32', 13),
('user33', 10),
('user34', 6),
('user35', 15),
('user36', 20),
('user37', 8),
('user38', 12),
('user39', 9),
('user40', 14),
('user41', 11),
('user42', 7),
('user43', 13),
('user44', 10),
('user45', 6),
('user46', 15),
('user47', 20),
('user48', 8),
('user49', 12),
('user50', 9);